apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skillsync
  namespace: skillsync
spec:
  rules:
    - host: skillsync.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skillsync-core
                port:
                  name: http
